[versions]
idea = "242.8057" # (see https://plugins.jetbrains.com/docs/intellij/android-studio-releases-list.html)
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }

[libraries]
autoService = "com.google.auto.service:auto-service-annotations:1.1.1"
autoService-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.1.0"

classgraph = "io.github.classgraph:classgraph:4.8.172"

intellij-core = { module = "com.jetbrains.intellij.platform:core", version.ref = "idea" }
intellij-util = { module = "com.jetbrains.intellij.platform:util", version.ref = "idea" }

javapoet = "com.squareup:javapoet:1.13.0"

kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-annotationProcessingEmbeddable = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-embeddable", version.ref = "kotlin" }
kotlin-scriptingCompiler = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kotlinpoet = "com.squareup:kotlinpoet:1.16.0"

ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "ksp" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

okio = "com.squareup.okio:okio:3.9.0"

truth = { module = "com.google.truth:truth", version = "1.4.2" }
junit = "junit:junit:4.13.2"
mockito = "org.mockito:mockito-core:5.11.0"
mockitoKotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
assertJ = "org.assertj:assertj-core:3.25.3"